services:
  - type: web
    name: nextjs-supabase-prisma
    env: node
    plan: free
    buildCommand: npm install && npm run db:generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
